name: 'Anu LMS'
description: 'Sets up the basics of the ANU Learning Management System.'
type: 'Site'
install:
  - anu_lms
config:
  import:
    anu_lms: '*'
    paragraphs: '*'
    paragraphs_browser: '*'
